name: isolated_benchmarks
description: Isolated benchmarks for excel_community and excel_plus.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  excel_community:
    path: ../
  excel_plus: ^0.0.5
